= Getting support for Micrometer

== GitHub issues
We choose not to use GitHub issues for general usage questions and support, preferring to
use issues solely for the tracking of bugs and enhancements. If you have a general
usage question please do not open a GitHub issue, but use one of the other channels
described below.

If you are reporting a bug, please help to speed up problem diagnosis by providing as
much information as possible. Ideally, that would include a small sample project that
reproduces the problem.

== Stack Overflow
The Micrometer community monitors the
https://stackoverflow.com/tags/micrometer[`micrometer`] tag on Stack Overflow. Before
asking a question, please familiarize yourself with Stack Overflow's
https://stackoverflow.com/help/how-to-ask[advice on how to ask a good question].

== Slack
If you want to discuss something or have a question that isn't suited to Stack Overflow,
the Micrometer community chat in the https://slack.micrometer.io[micrometer-metrics Slack].
