[[overview]]
= OkHttpClient Instrumentation

Micrometer supports https://square.github.io/okhttp/[OkHttp Client] instrumentation through Observation and metrics.

[[okhttpclient-observation]]
== OkHttpClient Observation

Below you can find an example of how to instrument OkHttp Client with xref:observation.adoc[Micrometer Observation]. That means that depending on your Observation Handler configuration you instrument once, and can have multiple benefits out of it (e.g. metrics, distributed tracing).

[source,java,subs=+attributes]
-----
// Setting up instrumentation
include::{include-core-test-java}/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationInterceptorTest.java[tags=setup, indent=0]

// Usage example
include::{include-core-test-java}/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationInterceptorTest.java[tags=example, indent=0]
-----

The builder allows to change the default `ObservationConvention` as follows.

[source,java,subs=+attributes]
-----
// Setting up instrumentation with custom convention
include::{include-core-test-java}/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationInterceptorTest.java[tags=custom_convention, indent=0]
-----

[[okhttpclient-metrics]]
== OkHttpClient Metrics

Micrometer supports binding metrics to `OkHttpClient` through `EventListener`.

You can collect metrics from `OkHttpClient` by adding `OkHttpMetricsEventListener`, as follows:

[source,java]
----
OkHttpClient client = new OkHttpClient.Builder()
    .eventListener(OkHttpMetricsEventListener.builder(registry, "okhttp.requests")
        .tags(Tags.of("foo", "bar"))
        .build())
    .build();
----

NOTE: The `uri` tag is usually limited to URI patterns to mitigate tag cardinality explosion, but `OkHttpClient` does not
provide URI patterns. We provide `URI_PATTERN` header to support `uri` tag, or you can configure a URI mapper to provide
your own tag values for `uri` tag.

To configure a URI mapper, you can use `uriMapper()`, as follows:

[source,java]
----
OkHttpClient client = new OkHttpClient.Builder()
    .eventListener(OkHttpMetricsEventListener.builder(registry, "okhttp.requests")
        .uriMapper(req -> req.url().encodedPath())
        .tags(Tags.of("foo", "bar"))
        .build())
    .build();
----

WARNING: The sample might trigger tag cardinality explosion, as a URI path itself is being used for tag values.
