[[context-propagation-installing]]
= Installing

Snapshots are published to https://repo.spring.io/snapshot for every successful build on the `main` branch and maintenance branches.

Milestone releases are published to https://repo.spring.io/milestone. Include that as a Maven repository in your build
configuration to use milestone releases. Note that milestone releases are for testing purposes and are not intended for
production use.

It is recommended to use the BOM provided by Micrometer (or your framework if any), you can see how to configure it xref:../installing.adoc[here]. The examples below assume you are using a BOM.

== Gradle

After the BOM is xref:../installing.adoc[configured], the following example adds Context Propagation in Gradle:

[source,groovy]
----
implementation 'io.micrometer:context-propagation'
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

== Maven

After the BOM is xref:../installing.adoc[configured], the following example adds Context Propagation in Maven:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>context-propagation</artifactId>
    </dependency>
</dependencies>
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.
