[[micrometer-observation-handler]]
= Observation Handler

A popular way to record them is storing the start state in a `Timer.Sample` instance and stopping it when the event has ended.
Recording such measurements could look like this:

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=timer,indent=0]
-----

If you want to have more observation options (such as metrics and tracing out of the box plus anything else you will plug in) then you'll need to rewrite that code to use the `Observation` API.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=observation,indent=0]
-----

One of the new features in Micrometer 1.10 is the ability to register "handlers" (`ObservationHandler`) that are notified about the lifecycle event of an observation (e.g.: you can run custom code when an observation is started/stopped).
Using this feature lets you add tracing capabilities to your existing metrics instrumentation (see: `DefaultTracingObservationHandler`). The implementation of these handlers does not need to be tracing related, it is completely up to you how you are going to implement them (e.g.: you can add logging capabilities) if you want.

[[micrometer-observation-context]]
== Observation.Context

In order to pass information between the instrumented code and the handler (or between handler methods, e.g.: `onStart` and `onStop`), you can utilize an `Observation.Context`. An `Observation.Context` is a `Map`-like container that can store values for you while your handler can access the data inside the context.

[[micrometer-observation-handler-example]]
== ObservationHandler Example

Based on this, we can implement a simple handler that lets the users know about its invocations by printing them out to `stdout`.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=simple_handler,indent=0]
-----

You need to register the handler to the `ObservationRegistry`.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=register_handler,indent=0]
-----

You can use the `observe` method to instrument your codebase.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=instrumenting_code,indent=0]
-----

You can also take full control of the scoping mechanism.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=manual_scoping,indent=0]
-----

[[micrometer-observation-events]]
== Signaling Errors and Arbitrary Events

When **instrumenting** code we might want to signal that an error happened or signal that an arbitrary event happened. The observation API lets us do it via it `error` and `event` methods.

One use-case for signaling arbitrary event can be attaching annotations to `Span` for Distributed Tracing but you can also process them however you want in your own handler, e.g.: emit log events based on them.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=error_and_event,indent=0]
-----

[[micrometer-observation-convention-example]]
== Observation.ObservationConvention Example

When **instrumenting** code we want to provide sensible defaults for tags but also we want to allow users to easily change those defaults. An `ObservationConvention` interface is a description of what tags and name we should create for an `Observation.Context`. See the full usage example of an instrumentation together with overriding the default tags.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=tax_example,indent=0]
-----

Below you can find an example of setting the whole code together.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=observation_convention_example,indent=0]
-----

[[micrometer-observation-predicates-filters]]
== Observation Predicates and Filters

To globally disable observations under given conditions you can use an `ObservationPredicate`. To mutate the `Observation.Context` you can use an `ObservationFilter`.

To set these just call `ObservationRegistry#observationConfig()#observationPredicate()` and `ObservationRegistry#observationConfig()#observationFilter()` methods respectively.

Below you can find an example of predicates and filters.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationConfiguringTests.java[tags=predicate_and_filter,indent=0]
-----

[[micrometer-observation-annotations]]
== Using Annotations With @Observed

If you have turned on Aspect Oriented Programming (e.g. via `org.aspectj:aspectjweaver`) you can use the `@Observed` annotation to create observations. You can put that annotation either on a method to observe it or a class to observe all methods in it. Let's look at the following example.

Here you can see an `ObservedService` that has an annotation on a method.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=observed_service,indent=0]
-----

The following test asserts whether the proper observation gets created when a proxied `ObservedService` instance gets called.

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationHandlerTests.java[tags=observed_aop,indent=0]
-----
