[[micrometer-observation-testing]]
= Testing

Micrometer Observation comes with the `micrometer-observation-test` module, which lets you unit-test your Observations.

[[micrometer-observation-installing]]
== Installing

It is recommended to use the BOM provided by Micrometer (or your framework if any), you can see how to configure it xref:../installing.adoc[here]. The examples below assume you are using a BOM.

=== Gradle

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,groovy]
-----
testImplementation 'io.micrometer:micrometer-observation-test'
-----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

=== Maven

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,xml]
-----
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-observation-test</artifactId>
    <scope>test</scope>
</dependency>
-----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

[[micrometer-observation-runnning]]
== Running Observation Unit Tests

Suppose you have the following production code. It will create an observation with two tags (low and high cardinality) and then call `observe` to start the observation, put it in scope, close the scope, and stop the observation:

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationTestingTests.java[tags=example,indent=0]
-----

To unit-test this code, you can use the `TestObservationRegistry` class:

[source,java,subs=+attributes]
-----
include::{include-java}/observation/ObservationTestingTests.java[tags=test,indent=0]
-----
