[[concepts]]
= Concepts

[[concepts-purpose]]
== Purpose

Micrometer is a metrics instrumentation library for JVM-based applications. It provides a simple facade over the instrumentation clients for the most popular monitoring systems, letting you instrument your JVM-based application code without vendor lock-in. It is designed to add little to no overhead to your metrics collection activity while maximizing the portability of your metrics effort.

Starting from Micrometer 1.10, Micrometer provides the xref:./observation.adoc[Observation API] and a plugin mechanism that lets you add capabilities, including the tracing features. You can read more about tracing in the https://docs.micrometer.io/tracing/reference/[Micrometer Tracing documentation].

For better understanding of the differences among these different types of systems (Metrics, Distributed Tracing, and Logging) we recommend Adrian Cole's talk, titled https://www.youtube.com/watch?v=juP9VApKy_I[Observability 3 Ways]. To learn more about Micrometer Observation API, we recommend Tommy Ludwig's and Marcin Grzejszczak's talk, titled https://www.youtube.com/watch?v=fh3VbrPvAjg[Observability of Your Application] and Tommy Ludwig's and Jonatan Ivanov's talk, titled https://www.youtube.com/watch?v=Qyku6cR6ADY[Micrometer Mastery].

[[concepts-dependencies]]
== Dependencies

The `micrometer-core` module aims to have minimal dependencies.
It does not require any third-party (non-Micrometer) dependencies on the classpath at compile time for applications that use Micrometer, except for https://jspecify.dev/[JSpecify].

Use of the xref:./concepts/timers.adoc#_pause_detection[pause detection] feature requires the https://github.com/LatencyUtils/LatencyUtils[LatencyUtils] dependency (`org.latencyutils:LatencyUtils`) to be available on the classpath at runtime.
Micrometer does not include LatencyUtils on the runtime classpath by default because pause detection is turned off by default.

If you use xref:./concepts/histogram-quantiles.adoc[client-side percentiles], you need https://github.com/HdrHistogram/HdrHistogram[HdrHistogram] on the classpath at runtime. If you do not use client-side percentiles, you may exclude HdrHistogram from your application's runtime classpath.
