description = "MeterRegistry implementation for AppOptics. This module is deprecated for removal due to AppOptics' End of Life Announcement."

dependencies {
    api project(':micrometer-core')

    implementation libs.slf4jApi

    testImplementation project(':micrometer-test')
    testImplementation libs.mockitoCore5
}
