import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    alias(libs.plugins.shadow)
}

description = 'Publishes Micrometer meters in OTLP format'

dependencies {
    api project(':micrometer-core')

    implementation platform(libs.openTelemetry.bom)
    implementation(libs.openTelemetry.exporter.otlp.common) {
        exclude group: 'io.opentelemetry', module: 'opentelemetry-sdk-extension-autoconfigure-spi'
    }
    implementation libs.openTelemetry.sdk.metrics

    testImplementation project(':micrometer-test')
    testImplementation libs.systemStubsJupiter
    testImplementation libs.restAssured
    testImplementation libs.testcontainers.junitJupiter
    testImplementation libs.awaitility
    testImplementation libs.mockitoCore5
    testImplementation libs.logbackLatest
    testImplementation(platform(libs.prometheusMetricsBom))
    testImplementation libs.prometheusMetricsExpositionFormats
}

tasks.named('jar') {
    enabled = false
}

def shadowJar = tasks.named('shadowJar', ShadowJar) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    failOnDuplicateEntries = true
    configurations.set([project.configurations.compileClasspath])
    archiveClassifier.set('')
    dependencies {
        include(dependency('io.opentelemetry:.*'))
    }
    exclude("META-INF/maven/**")
    relocate 'io.opentelemetry', 'io.micrometer.registry.otlp.shaded.io.opentelemetry'
    metaInf {
        from "$rootDir/LICENSE"
        from "$rootDir/NOTICE"
    }
    mergeServiceFiles()
}

tasks.japicmp.dependsOn(shadowJar)

publishing {
    publications {
        withType(MavenPublication) {
            pom.withXml {
                asNode()
                    .dependencies
                    .dependency
                    .findAll { ['opentelemetry-exporter-otlp-common', 'opentelemetry-sdk-metrics'].contains(it.artifactId.text()) }
                    .each { it.parent().remove(it) }
            }
        }
    }
}

dockerTest {
    systemProperty 'otel-collector-image.version', '0.152.1'
}
