/**
 * Copyright 2017 VMware, Inc.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote.proto
package io.logz.listener.inputs.prometheus.protocol;

public final class Remote {
    private Remote() { }
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface WriteRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:prometheus.WriteRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries>
        getTimeseriesList();
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries getTimeseries(int index);
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        int getTimeseriesCount();
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        java.util.List<? extends io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder>
        getTimeseriesOrBuilderList();
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder getTimeseriesOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code prometheus.WriteRequest}
     */
    public  static final class WriteRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:prometheus.WriteRequest)
            WriteRequestOrBuilder {
        // Use WriteRequest.newBuilder() to construct.
        private WriteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private WriteRequest() {
            timeseries_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private WriteRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                timeseries_ = new java.util.ArrayList<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            timeseries_.add(
                                    input.readMessage(io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    timeseries_ = java.util.Collections.unmodifiableList(timeseries_);
                }
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.logz.listener.inputs.prometheus.protocol.Remote.internal_static_prometheus_WriteRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.logz.listener.inputs.prometheus.protocol.Remote.internal_static_prometheus_WriteRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.class, io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.Builder.class);
        }

        public static final int TIMESERIES_FIELD_NUMBER = 1;
        private java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries> timeseries_;
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        public java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries> getTimeseriesList() {
            return timeseries_;
        }
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        public java.util.List<? extends io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder>
        getTimeseriesOrBuilderList() {
            return timeseries_;
        }
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        public int getTimeseriesCount() {
            return timeseries_.size();
        }
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries getTimeseries(int index) {
            return timeseries_.get(index);
        }
        /**
         * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
         */
        public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder getTimeseriesOrBuilder(
                int index) {
            return timeseries_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < timeseries_.size(); i++) {
                output.writeMessage(1, timeseries_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < timeseries_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, timeseries_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest)) {
                return super.equals(obj);
            }
            io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest other = (io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest) obj;

            boolean result = true;
            result = result && getTimeseriesList()
                    .equals(other.getTimeseriesList());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (getTimeseriesCount() > 0) {
                hash = (37 * hash) + TIMESERIES_FIELD_NUMBER;
                hash = (53 * hash) + getTimeseriesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException  {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code prometheus.WriteRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:prometheus.WriteRequest)
                io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.logz.listener.inputs.prometheus.protocol.Remote.internal_static_prometheus_WriteRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.logz.listener.inputs.prometheus.protocol.Remote.internal_static_prometheus_WriteRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.class, io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.Builder.class);
            }

            // Construct using io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getTimeseriesFieldBuilder();
                }
            }
            public Builder clear() {
                super.clear();
                if (timeseriesBuilder_ == null) {
                    timeseries_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else  {
                    timeseriesBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType()  {
                return io.logz.listener.inputs.prometheus.protocol.Remote.internal_static_prometheus_WriteRequest_descriptor;
            }

            public io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest getDefaultInstanceForType() {
                return io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.getDefaultInstance();
            }

            public io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest build() {
                io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest buildPartial() {
                io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest result = new io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest(this);
                int from_bitField0_ = bitField0_;
                if (timeseriesBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        timeseries_ = java.util.Collections.unmodifiableList(timeseries_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.timeseries_ = timeseries_;
                } else {
                    result.timeseries_ = timeseriesBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest) {
                    return mergeFrom((io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest other) {
                if (other == io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest.getDefaultInstance()) return this;
                if (timeseriesBuilder_ == null) {
                    if (!other.timeseries_.isEmpty()) {
                        if (timeseries_.isEmpty()) {
                            timeseries_ = other.timeseries_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureTimeseriesIsMutable();
                            timeseries_.addAll(other.timeseries_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.timeseries_.isEmpty()) {
                        if (timeseriesBuilder_.isEmpty()) {
                            timeseriesBuilder_.dispose();
                            timeseriesBuilder_ = null;
                            timeseries_ = other.timeseries_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            timeseriesBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getTimeseriesFieldBuilder() : null;
                        } else {
                            timeseriesBuilder_.addAllMessages(other.timeseries_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries> timeseries_ =
                    java.util.Collections.emptyList();
            private void ensureTimeseriesIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    timeseries_ = new java.util.ArrayList<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries>(timeseries_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder> timeseriesBuilder_;

            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries> getTimeseriesList() {
                if (timeseriesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(timeseries_);
                } else {
                    return timeseriesBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public int getTimeseriesCount() {
                if (timeseriesBuilder_ == null) {
                    return timeseries_.size();
                } else {
                    return timeseriesBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries getTimeseries(int index) {
                if (timeseriesBuilder_ == null) {
                    return timeseries_.get(index);
                } else {
                    return timeseriesBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder setTimeseries(
                    int index, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries value) {
                if (timeseriesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTimeseriesIsMutable();
                    timeseries_.set(index, value);
                    onChanged();
                } else {
                    timeseriesBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder setTimeseries(
                    int index, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder builderForValue) {
                if (timeseriesBuilder_ == null) {
                    ensureTimeseriesIsMutable();
                    timeseries_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    timeseriesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder addTimeseries(io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries value) {
                if (timeseriesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTimeseriesIsMutable();
                    timeseries_.add(value);
                    onChanged();
                } else {
                    timeseriesBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder addTimeseries(
                    int index, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries value) {
                if (timeseriesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTimeseriesIsMutable();
                    timeseries_.add(index, value);
                    onChanged();
                } else {
                    timeseriesBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder addTimeseries(
                    io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder builderForValue) {
                if (timeseriesBuilder_ == null) {
                    ensureTimeseriesIsMutable();
                    timeseries_.add(builderForValue.build());
                    onChanged();
                } else {
                    timeseriesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder addTimeseries(
                    int index, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder builderForValue) {
                if (timeseriesBuilder_ == null) {
                    ensureTimeseriesIsMutable();
                    timeseries_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    timeseriesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder addAllTimeseries(
                    java.lang.Iterable<? extends io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries> values) {
                if (timeseriesBuilder_ == null) {
                    ensureTimeseriesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, timeseries_);
                    onChanged();
                } else {
                    timeseriesBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder clearTimeseries() {
                if (timeseriesBuilder_ == null) {
                    timeseries_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    timeseriesBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public Builder removeTimeseries(int index) {
                if (timeseriesBuilder_ == null) {
                    ensureTimeseriesIsMutable();
                    timeseries_.remove(index);
                    onChanged();
                } else {
                    timeseriesBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder getTimeseriesBuilder(
                    int index) {
                return getTimeseriesFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder getTimeseriesOrBuilder(
                    int index) {
                if (timeseriesBuilder_ == null) {
                    return timeseries_.get(index);  } else {
                    return timeseriesBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public java.util.List<? extends io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder>
            getTimeseriesOrBuilderList() {
                if (timeseriesBuilder_ != null) {
                    return timeseriesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(timeseries_);
                }
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder addTimeseriesBuilder() {
                return getTimeseriesFieldBuilder().addBuilder(
                        io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder addTimeseriesBuilder(
                    int index) {
                return getTimeseriesFieldBuilder().addBuilder(
                        index, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.getDefaultInstance());
            }
            /**
             * <code>repeated .prometheus.TimeSeries timeseries = 1;</code>
             */
            public java.util.List<io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder>
            getTimeseriesBuilderList() {
                return getTimeseriesFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder>
            getTimeseriesFieldBuilder() {
                if (timeseriesBuilder_ == null) {
                    timeseriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeries.Builder, io.logz.listener.inputs.prometheus.protocol.Types.TimeSeriesOrBuilder>(
                            timeseries_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    timeseries_ = null;
                }
                return timeseriesBuilder_;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:prometheus.WriteRequest)
        }

        // @@protoc_insertion_point(class_scope:prometheus.WriteRequest)
        private static final io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest();
        }

        public static io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<WriteRequest>
                PARSER = new com.google.protobuf.AbstractParser<WriteRequest>() {
            public WriteRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new WriteRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<WriteRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<WriteRequest> getParserForType() {
            return PARSER;
        }

        public io.logz.listener.inputs.prometheus.protocol.Remote.WriteRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_prometheus_WriteRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_prometheus_WriteRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014remote.proto\022\nprometheus\032\013types.proto\"" +
                        ":\n\014WriteRequest\022*\n\ntimeseries\030\001 \003(\0132\026.pr" +
                        "ometheus.TimeSeriesB-\n+io.logz.listener." +
                        "inputs.prometheus.protocolb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                io.logz.listener.inputs.prometheus.protocol.Types.getDescriptor(),
                        }, assigner);
        internal_static_prometheus_WriteRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_prometheus_WriteRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_prometheus_WriteRequest_descriptor,
                new java.lang.String[] { "Timeseries", });
        io.logz.listener.inputs.prometheus.protocol.Types.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
