plugins {
    id 'java'
    alias(libs.plugins.aspectj)
}

description = 'AspectJ compile-time weaving test for Micrometer aspects'

// when project is built with jdk <17, aspectj compilation does not happen on micrometer-core
// skip this module when building with jdk <17
if (!javaLanguageVersion.canCompileOrRun(17)) {
    project.tasks.configureEach { task -> task.enabled = false }
}

dependencies {
    aspect project(':micrometer-core')
    implementation libs.aspectjrt

    testImplementation libs.assertj
}

test {
    useJUnitPlatform()
}
