= Micrometer Influx
:sectnums:
:system: influx

The InfluxData suite of tools supports real-time stream processing and storage of time-series data. It supports downsampling, automatically expiring and deleting unwanted data, as well as backup and restore.

The InfluxMeterRegistry supports the 1.x InfluxDB API as well as the v2 API.

== Installation and Configuration

Micrometer supports shipping metrics to InfluxDB directly or through Telegraf through the StatsD registry.

It is recommended to use the BOM provided by Micrometer (or your framework if any), you can see how to configure it xref:../installing.adoc[here]. The examples below assume you are using a BOM.

=== Direct to InfluxDB

==== Gradle

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,groovy]
----
implementation 'io.micrometer:micrometer-registry-influx'
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

==== Maven

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-influx</artifactId>
</dependency>
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

Metrics are rate-aggregated and pushed to InfluxDB on a periodic interval. Rate aggregation performed by the registry yields datasets that are quite similar to those produced by Telegraf. The following example configures a meter registry for InfluxDB:

.InfluxDB 1.x configuration example
[source, java]
----
InfluxConfig config = new InfluxConfig() {
    @Override
    public Duration step() {
        return Duration.ofSeconds(10);
    }

    @Override
    public String db() {
        return "mydb";
    }

    @Override
    public String get(String k) {
        return null; // accept the rest of the defaults
    }
};
MeterRegistry registry = new InfluxMeterRegistry(config, Clock.SYSTEM);
----

To ship metrics to InfluxDB 2.x, make sure to configure the `org` and `bucket` to which to write the metrics, as well as the authentication `token`:

.InfluxDB v2 configuration example
[source, java]
----
InfluxConfig config = new InfluxConfig() {

    @Override
    public String org() {
        return "myorg";
    }

    @Override
    public String bucket() {
        return "app-metrics";
    }

    @Override
    public String token() {
        return "auth_token_here"; // FIXME: This should be securely bound rather than hard-coded, of course.
    }

    @Override
    public String get(String k) {
        return null; // accept the rest of the defaults
    }
};
MeterRegistry registry = new InfluxMeterRegistry(config, Clock.SYSTEM);
----

`InfluxConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null`, you instead bind it to a property source, you can override the default configuration.
For the full set of configurable options and their defaults, see the
https://javadoc.io/doc/io.micrometer/micrometer-registry-influx/latest/io/micrometer/influx/InfluxConfig.html[`InfluxConfig` Javadoc].

If you configure Micrometer through Spring Boot, refer to the
https://docs.spring.io/spring-boot/reference/actuator/metrics.html[Spring Boot reference documentation]
for the corresponding configuration properties.

=== Through Telegraf

Telegraf is a StatsD agent that expects a modified flavor of the StatsD line protocol.

==== Gradle

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,groovy]
----
implementation 'io.micrometer:micrometer-registry-statsd'
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

==== Maven

After the BOM is xref:../installing.adoc[configured], add the following dependency:

[source,xml]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-registry-statsd</artifactId>
</dependency>
----

NOTE: The version is not needed for this dependency since it is defined by the BOM.

Metrics are shipped immediately over UDP to Telegraf by using Telegraf's flavor of the StatsD line protocol:

[source,java]
----
StatsdConfig config = new StatsdConfig() {
    @Override
    public String get(String k) {
        return null;
    }

    @Override
    public StatsdFlavor flavor() {
        return StatsdFlavor.Telegraf;
    }
};

MeterRegistry registry = new StatsdMeterRegistry(config, Clock.SYSTEM);
----
