name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    # Until v6 is released
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@f8e8b7b704f2d40794895560c6f02bb56df1585c
    with:
      autoMerge: true
      mergeArguments: --auto --squash
