name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    # Until v6 is released
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@c23d02e2e23b5b5f22222afb49db626c83990fed
    with:
      autoMerge: true
      mergeArguments: --auto --squash
