name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    # Until v6 is released
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@b10e656d18b203b96c745b1bb5fc1b1869034aef
    with:
      autoMerge: true
      mergeArguments: --auto --squash
